# This file was generated by GoReleaser. DO NOT EDIT.
cask "quicsql" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "d2cf9ab37f543b43679b79f0cf72706b562d1a351ca5c35ecbf240fad34bce13"
      url "https://github.com/quicsql/quicsql/releases/download/v#{version}/quicsql_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9df6a2549196d34913f48d96016905534975cf14d465b42147d790fa36eb6ee9"
      url "https://github.com/quicsql/quicsql/releases/download/v#{version}/quicsql_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f16dd3ba3d21bffa12841538a75c96a8f32f52e58aa0f7ba2ef9bd351d8f52e9"
      url "https://github.com/quicsql/quicsql/releases/download/v#{version}/quicsql_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "521b8a7a1e17a9e174afc7febff07fba38726549472f29af4aa9bddde1bdfc04"
      url "https://github.com/quicsql/quicsql/releases/download/v#{version}/quicsql_#{version}_linux_arm64.tar.gz"
    end
  end

  name "quicsql"
  desc "CGo-free SQLite network server (native JSON + libSQL Hrana)"
  homepage "https://github.com/quicsql/quicsql"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quicsql"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quicsql"]
    end
  end

  # No zap stanza required

end
