# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quicsql < Formula
  desc "CGo-free SQLite network server (native JSON + libSQL Hrana)"
  homepage "https://github.com/quicsql/quicsql"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.3/quicsql_0.5.3_darwin_amd64.tar.gz"
      sha256 "ebdbe22f9e10237d701e420cc2453d8a267f65f62696bc8556f6185a87d5df90"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.3/quicsql_0.5.3_darwin_arm64.tar.gz"
      sha256 "c86b8aed5bf5121c3bd51c9ab39209ab9ba2eb400f6f13bd7a96fdc6f3333a71"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.3/quicsql_0.5.3_linux_amd64.tar.gz"
      sha256 "d033dc209a041fb8145d36cf790bb1231231ec12b6fc1e9a90cb959f7b2b12f7"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.3/quicsql_0.5.3_linux_arm64.tar.gz"
      sha256 "cc871be0b6e39a635055812be75527c4c8fb6e6965b6ed70c193911ee6f3702e"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  def post_install
    (var/"quicsql").mkpath
    (var/"log").mkpath
    unless (etc/"quicsql/quicsql.yaml").exist?
      (etc/"quicsql").mkpath
      (etc/"quicsql/quicsql.yaml").write <<~EOS
        # quicSQL config, seeded by Homebrew — localhost-only HTTP/1.1, no TLS,
        # no auth, no databases yet. Docs: https://github.com/quicsql/quicsql
        # After editing: brew services restart quicsql
        server:
          data_dir: #{var}/quicsql
        listeners:
          - {name: h1, transport: h1, address: 127.0.0.1:7775}
      EOS
    end
  end

  def caveats
    <<~EOS
      Config: #{etc}/quicsql/quicsql.yaml (edit, then `brew services restart quicsql`)
      Data:   #{var}/quicsql
      Logs:   #{var}/log/quicsql.log

      Run as a background service:
        brew services start quicsql
    EOS
  end

  service do
    run [opt_bin/"quicsql", "-config", etc/"quicsql/quicsql.yaml"]
    keep_alive true
    working_dir var/"quicsql"
    log_path var/"log/quicsql.log"
    error_log_path var/"log/quicsql.log"
  end

  test do
    system "#{bin}/quicsql", "-version"
  end
end
