# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quicsql < Formula
  desc "CGo-free SQLite network server (native JSON + libSQL Hrana)"
  homepage "https://github.com/quicsql/quicsql"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quicsql/quicsql/releases/download/v0.6.0/quicsql_0.6.0_darwin_amd64.tar.gz"
      sha256 "0b78abc11844e76772e0307b84ceefe39af1abd942d7abe2afe0ad16fbeaef34"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quicsql/quicsql/releases/download/v0.6.0/quicsql_0.6.0_darwin_arm64.tar.gz"
      sha256 "123a756d0d3140081a15256ee537ccac8bc8f1c777b7d17dbde454c8b55390b1"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.6.0/quicsql_0.6.0_linux_amd64.tar.gz"
      sha256 "73b63b16fdf9a4d3d807e2f342a876c5801bfda0a15366f89818322638baaeae"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.6.0/quicsql_0.6.0_linux_arm64.tar.gz"
      sha256 "f5e814f44ab152e0fc6e199551b3383a0db3daacfb6baf3c2b8a742268939873"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  def post_install
    (var/"quicsql").mkpath
    (var/"log").mkpath
    unless (etc/"quicsql/quicsql.yaml").exist?
      (etc/"quicsql").mkpath
      (etc/"quicsql/quicsql.yaml").write <<~EOS
        # quicSQL config, seeded by Homebrew — localhost-only HTTP/1.1, no TLS,
        # no auth, no databases yet. Docs: https://github.com/quicsql/quicsql
        # After editing: brew services restart quicsql
        server:
          data_dir: #{var}/quicsql
        listeners:
          - {name: h1, transport: h1, address: 127.0.0.1:7775}
      EOS
    end
  end

  def caveats
    <<~EOS
      Config: #{etc}/quicsql/quicsql.yaml (edit, then `brew services restart quicsql`)
      Data:   #{var}/quicsql
      Logs:   #{var}/log/quicsql.log

      Run as a background service:
        brew services start quicsql
    EOS
  end

  service do
    run [opt_bin/"quicsql", "-config", etc/"quicsql/quicsql.yaml"]
    keep_alive true
    working_dir var/"quicsql"
    log_path var/"log/quicsql.log"
    error_log_path var/"log/quicsql.log"
  end

  test do
    system "#{bin}/quicsql", "-version"
  end
end
