# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quicsql < Formula
  desc "CGo-free SQLite network server (native JSON + libSQL Hrana)"
  homepage "https://github.com/quicsql/quicsql"
  version "0.5.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.2/quicsql_0.5.2_darwin_amd64.tar.gz"
      sha256 "72796b3ce0eda999d81b7110293d7a1521dbbcd0e1bf8a0851feb7803965f59e"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.2/quicsql_0.5.2_darwin_arm64.tar.gz"
      sha256 "446e85c57bb94d9902c24d7fd0ae551c5c36255d6ebc6115d7b36784cb9ceb61"

      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.2/quicsql_0.5.2_linux_amd64.tar.gz"
      sha256 "bdc04fad70035c9573b9f63f78f6db6bb91450497a68f2e53d827b2a35cdcb68"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quicsql/quicsql/releases/download/v0.5.2/quicsql_0.5.2_linux_arm64.tar.gz"
      sha256 "eed08faa3ff8a66e4fd89284cc7237d93243e9a8b9e18845a8f7d1d646669b67"
      define_method(:install) do
        bin.install "quicsql"
      end
    end
  end

  def post_install
    (var/"quicsql").mkpath
    (var/"log").mkpath
    unless (etc/"quicsql/quicsql.yaml").exist?
      (etc/"quicsql").mkpath
      (etc/"quicsql/quicsql.yaml").write <<~EOS
        # quicSQL config, seeded by Homebrew — localhost-only HTTP/1.1, no TLS,
        # no auth, no databases yet. Docs: https://github.com/quicsql/quicsql
        # After editing: brew services restart quicsql
        server:
          data_dir: #{var}/quicsql
        listeners:
          - {name: h1, transport: h1, address: 127.0.0.1:7775}
      EOS
    end
  end

  def caveats
    <<~EOS
      Config: #{etc}/quicsql/quicsql.yaml (edit, then `brew services restart quicsql`)
      Data:   #{var}/quicsql
      Logs:   #{var}/log/quicsql.log

      Run as a background service:
        brew services start quicsql
    EOS
  end

  service do
    run [opt_bin/"quicsql", "-config", etc/"quicsql/quicsql.yaml"]
    keep_alive true
    working_dir var/"quicsql"
    log_path var/"log/quicsql.log"
    error_log_path var/"log/quicsql.log"
  end

  test do
    system "#{bin}/quicsql", "-version"
  end
end
